version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: [ "CMD-SHELL", "nc -z kafka 9092 || exit 1" ]
      interval: 10s
      retries: 10
    depends_on:
      - zookeeper

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: produtos
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

networks:
  app_network:
    driver: bridge
